// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kargotakipsistemi;

#nullable disable

namespace kargotakipsistemi.Migrations
{
    [DbContext(typeof(KtsContext))]
    [Migration("20251127083843_mig5")]
    partial class mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kargotakipsistemi.Entities.Adres", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresId"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdresBaslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdresTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("BinaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Daire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EkAciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("KapiNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Kat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MahalleId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AdresId");

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.HasIndex("MahalleId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracId"));

                    b.Property<string>("AracTip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GpsKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("KapasiteKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("AracId");

                    b.HasIndex("SubeId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Gonderi", b =>
                {
                    b.Property<int>("GonderiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GonderiId"));

                    b.Property<decimal>("Agirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AliciAdresId")
                        .HasColumnType("int");

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<string>("Boyut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("EkMasraf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GonderenAdresId")
                        .HasColumnType("int");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GonderiTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IadeDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("IndirimTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("IptalTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KuryeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TahminiTeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TakipNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TeslimEdilenKisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeslimatTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GonderiId");

                    b.HasIndex("AliciAdresId");

                    b.HasIndex("AliciId");

                    b.HasIndex("GonderenAdresId");

                    b.HasIndex("GonderenId");

                    b.HasIndex("KuryeId");

                    b.ToTable("Gonderiler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.GonderiDurumGecmis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("DurumAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GonderiId")
                        .HasColumnType("int");

                    b.Property<string>("IlgiliKisiAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IlgiliKisiTel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("IslemBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IslemBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemSonucu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<bool>("SonDurumMu")
                        .HasColumnType("bit");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeslimatKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("GonderiId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SubeId");

                    b.ToTable("GonderiDurumGecmisi");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.IadeIptalIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DosyaLinki")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GonderiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IadeTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("IslemBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IslemBaslatanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IslemBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemDurumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("IslemOnaylayanId")
                        .HasColumnType("int");

                    b.Property<string>("IslemSonucu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("RedNedeni")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GonderiId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SubeId");

                    b.ToTable("IadeIptalIslemleri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Il", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlId"));

                    b.Property<string>("IlAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IlId");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceId"));

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IlceId");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Mahalle", b =>
                {
                    b.Property<int>("MahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MahalleId"));

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("MahalleAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MahalleId");

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.MusteriAdres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("AdresTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriAdresleri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.MusteriDestek", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CevapTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CozumAciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CozumDurumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosyaLinki")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GonderenId")
                        .HasColumnType("int");

                    b.Property<int>("GonderiId")
                        .HasColumnType("int");

                    b.Property<string>("IlgiliKisiAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IlgiliKisiTel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("IslemSonucu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kanal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KayitId");

                    b.HasIndex("AliciId");

                    b.HasIndex("GonderenId");

                    b.HasIndex("GonderiId");

                    b.HasIndex("PersonelId");

                    b.ToTable("MusteriDestekleri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.OdemeFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AliciAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("EkMasraf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FaturaAdresId")
                        .HasColumnType("int");

                    b.Property<int>("GonderiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OdemeNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FaturaAdresId");

                    b.HasIndex("GonderiId");

                    b.HasIndex("MusteriId");

                    b.ToTable("OdemeFaturalari");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EhliyetSinifi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("IseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IstenCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PersonelId");

                    b.HasIndex("AracId");

                    b.HasIndex("RolId");

                    b.HasIndex("SubeId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Sube", b =>
                {
                    b.Property<int>("SubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubeId"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CalismaSaatleri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<int?>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("SubeAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubeTip")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("SubeId");

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Adres", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Il", "Il")
                        .WithMany("Adresler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Ilce", "Ilce")
                        .WithMany("Adresler")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Mahalle", "Mahalle")
                        .WithMany("Adresler")
                        .HasForeignKey("MahalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Musteri")
                        .WithMany("Adresler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("kargotakipsistemi.Entities.Personel", "Personel")
                        .WithMany("Adresler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Il");

                    b.Navigation("Ilce");

                    b.Navigation("Mahalle");

                    b.Navigation("Musteri");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Arac", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Sube", "Sube")
                        .WithMany("Araclar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Gonderi", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Adres", "AliciAdres")
                        .WithMany()
                        .HasForeignKey("AliciAdresId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Alici")
                        .WithMany("GonderilerAlici")
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Adres", "GonderenAdres")
                        .WithMany()
                        .HasForeignKey("GonderenAdresId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Gonderen")
                        .WithMany("GonderilerGonderen")
                        .HasForeignKey("GonderenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Personel", "Kurye")
                        .WithMany()
                        .HasForeignKey("KuryeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alici");

                    b.Navigation("AliciAdres");

                    b.Navigation("Gonderen");

                    b.Navigation("GonderenAdres");

                    b.Navigation("Kurye");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.GonderiDurumGecmis", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Arac", "Arac")
                        .WithMany("GonderiDurumGecmisi")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kargotakipsistemi.Entities.Gonderi", "Gonderi")
                        .WithMany()
                        .HasForeignKey("GonderiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Personel", "Personel")
                        .WithMany("GonderiDurumGecmisi")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kargotakipsistemi.Entities.Sube", "Sube")
                        .WithMany("GonderiDurumGecmisi")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arac");

                    b.Navigation("Gonderi");

                    b.Navigation("Personel");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.IadeIptalIslem", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Gonderi", "Gonderi")
                        .WithMany()
                        .HasForeignKey("GonderiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Musteri")
                        .WithMany("IadeIptalIslemleri")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Personel", "Personel")
                        .WithMany("IadeIptalIslemleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kargotakipsistemi.Entities.Sube", "Sube")
                        .WithMany("IadeIptalIslemleri")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gonderi");

                    b.Navigation("Musteri");

                    b.Navigation("Personel");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Ilce", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Mahalle", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Ilce", "Ilce")
                        .WithMany("Mahalleler")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.MusteriAdres", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Adres", "Adres")
                        .WithMany()
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Musteri")
                        .WithMany("MusteriAdresleri")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.MusteriDestek", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Alici")
                        .WithMany("MusteriDestekleriAlici")
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Gonderen")
                        .WithMany("MusteriDestekleriGonderen")
                        .HasForeignKey("GonderenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Gonderi", "Gonderi")
                        .WithMany()
                        .HasForeignKey("GonderiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Personel", "Personel")
                        .WithMany("MusteriDestekleri")
                        .HasForeignKey("PersonelId");

                    b.Navigation("Alici");

                    b.Navigation("Gonderen");

                    b.Navigation("Gonderi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.OdemeFatura", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Adres", "FaturaAdres")
                        .WithMany()
                        .HasForeignKey("FaturaAdresId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("kargotakipsistemi.Entities.Gonderi", "Gonderi")
                        .WithMany()
                        .HasForeignKey("GonderiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Musteri", "Musteri")
                        .WithMany("OdemeFaturalari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FaturaAdres");

                    b.Navigation("Gonderi");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Personel", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Arac", "Arac")
                        .WithMany("Personeller")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("kargotakipsistemi.Entities.Rol", "Rol")
                        .WithMany("Personeller")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Sube", "Sube")
                        .WithMany("Personeller")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Rol");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Sube", b =>
                {
                    b.HasOne("kargotakipsistemi.Entities.Il", "Il")
                        .WithMany("Subeler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kargotakipsistemi.Entities.Ilce", "Ilce")
                        .WithMany("Subeler")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Il");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Arac", b =>
                {
                    b.Navigation("GonderiDurumGecmisi");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Il", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Ilceler");

                    b.Navigation("Subeler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Ilce", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Mahalleler");

                    b.Navigation("Subeler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Mahalle", b =>
                {
                    b.Navigation("Adresler");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Musteri", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("GonderilerAlici");

                    b.Navigation("GonderilerGonderen");

                    b.Navigation("IadeIptalIslemleri");

                    b.Navigation("MusteriAdresleri");

                    b.Navigation("MusteriDestekleriAlici");

                    b.Navigation("MusteriDestekleriGonderen");

                    b.Navigation("OdemeFaturalari");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Personel", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("GonderiDurumGecmisi");

                    b.Navigation("IadeIptalIslemleri");

                    b.Navigation("MusteriDestekleri");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Rol", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("kargotakipsistemi.Entities.Sube", b =>
                {
                    b.Navigation("Araclar");

                    b.Navigation("GonderiDurumGecmisi");

                    b.Navigation("IadeIptalIslemleri");

                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
